apiVersion: v1
kind: Secret
metadata:
#  name: mysql-secrets
  name: {{ .Chart.Name }}-secrets
#  namespace: mysql
#  namespace: {{ .Values.namespace }}
type: Opaque
data:
#  MYSQL_ROOT_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
#  MYSQL_USER: "YXBwX3VzZXI=" # Base64 encoding for "app_user"
#  MYSQL_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
  {{- range $key, $value := .Values.configs }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
