apiVersion: v1
kind: ServiceAccount
metadata:
  # Назва контролюється з values.yaml
  name: {{ .Values.serviceAccount.name }}
  # Назва namespace контролюється з values.yaml
  namespace: {{ .Values.namespace }}
