apiVersion: v1
kind: PersistentVolumeClaim
metadata:
#  name: pvc-data
  name: {{ .Chart.Name }}-data
#  namespace: todoapp
  namespace: {{ .Values.namespace }}
spec:
#  volumeName: pv-data
  volumeName: {{ .Chart.Name }}-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
#      storage: 1Gi
      storage: {{ .Values.pvc.storage }}
